package handlers

// package handlers imports http, and handles all communication between the
// client and server.

import (
	"errors"
	"fmt"
	"net/http"
	"path"
	"strings"
	"time"

	_ "github.com/jackc/pgx/stdlib"
	// TODO: import from github
	"../which"
)

func ListenAndServe(address string, handler *Root) error {
	return http.ListenAndServe(address, handler)
}

// == Root handler ================================

type Root struct {
	// child handlers
	StaticHandler *Static
	AuthHandler   *Auth
	QsHandler     *Qs
}

func NewRoot(userStore which.UserStore, sessionStore which.SessionStore, questionStore which.QuestionStore) *Root {
	root := &Root{
		StaticHandler: &Static{},
		AuthHandler:   NewAuth(userStore, sessionStore),
		QsHandler:     NewQs(sessionStore, questionStore),
	}
	return root
}

func (handler *Root) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	head, tail := shiftPath(req.URL.Path)
	if head == "qs" {
		req.URL.Path = tail
		handler.QsHandler.ServeHTTP(resp, req)
	} else if head == "auth" {
		req.URL.Path = tail
		handler.AuthHandler.ServeHTTP(resp, req)
	} else {
		req.URL.Path = head + tail
		handler.StaticHandler.ServeHTTP(resp, req)
	}
}

// == Static handler ================================
// serves files generated by Svelte (in /public)

type Static struct{}

func (handler *Static) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	http.ServeFile(resp, req, cleanPublicPath(req.URL.Path))
}

func cleanPublicPath(p string) string {
	cleaned := path.Clean("public/" + p)
	if cleaned != "public" && cleaned[:7] != "public/" {
		return "public/"
	}
	return cleaned
}

// == Shared helpers ================================

func shiftPath(p string) (head, tail string) {
	p = path.Clean("/" + p)
	i := strings.Index(p[1:], "/") + 1
	if i <= 0 {
		return p[1:], "/"
	}
	return p[1:i], p[i:]
}

func addCookie(resp http.ResponseWriter, name string, value string, expires time.Time) {
	cookie := http.Cookie{
		Name:    name,
		Value:   value,
		Expires: expires,
		Path:    "/",
	}
	http.SetCookie(resp, &cookie)
}

// returns a Session if the request has a valid session cookie, else error
// TODO: somewhat awkward - retrieves session from store using id from request data
func sessionFromRequest(req *http.Request, store which.SessionStore) (which.Session, error) {
	sessionCookie, err := req.Cookie("session")
	if err != nil {
		return which.Session{}, fmt.Errorf("failed to get session cookie from request: %v", err)
	}
	session, err := store.Fetch(sessionCookie.Value)
	if err != nil {
		return which.Session{}, fmt.Errorf("no session matching cookie: %v", err)
	}
	if session.ID != sessionCookie.Value {
		return which.Session{}, errors.New("session ID from db didn't match cookie (this should be impossible)")
	}
	if time.Now().After(session.Expires) {
		return which.Session{}, errors.New("session expired")
	}
	return session, nil
}
